### ISSUE TITLE
crashes the app with new lib com.google.android.gms:play-services-location:21.0.0

### ISSUE THREAD

**Issue by lavruxa** [yayaa/LocationManager#126]
Hi, it works great with old lib

implementation 'com.google.android.gms:play-services-location:20.0.0'

but crashes the app with new lib

implementation 'com.google.android.gms:play-services-location:21.0.0'

**Comment by andreabellitto** [comment]
Same for me

this is the log

`FATAL EXCEPTION: main
                                                                                                    Process: com.belandsoft.orariGTT, PID: 2696
                                                                                                    java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~sYk1RH4zDZQyH4ZUuKCgxw==/com.belandsoft.orariGTT-muZW1no5aM4JW7FchlbxSg==/base.apk!classes27.dex)
                                                                                                    	at com.yayandroid.locationmanager.providers.locationprovider.GooglePlayServicesLocationSource.requestLastLocation(GooglePlayServicesLocationSource.java:87)
                                                                                                    	at com.yayandroid.locationmanager.providers.locationprovider.GooglePlayServicesLocationProvider.get(GooglePlayServicesLocationProvider.java:81)
                                                                                                    	at com.yayandroid.locationmanager.providers.locationprovider.DispatcherLocationProvider.getLocationFromGooglePlayServices(DispatcherLocationProvider.java:212)
                                                                                                    	at com.yayandroid.locationmanager.providers.locationprovider.DispatcherLocationProvider.checkGooglePlayServicesAvailability(DispatcherLocationProvider.java:127)
                                                                                                    	at com.yayandroid.locationmanager.providers.locationprovider.DispatcherLocationProvider.get(DispatcherLocationProvider.java:107)
                                                                                                    	at com.yayandroid.locationmanager.LocationManager.permissionGranted(LocationManager.java:255)
                                                                                                    	at com.yayandroid.locationmanager.LocationManager.askForPermission(LocationManager.java:233)
                                                                                                    	at com.yayandroid.locationmanager.LocationManager.get(LocationManager.java:221)
                                                                                                    	at com.yayandroid.locationmanager.base.LocationBaseActivity.getLocation(LocationBaseActivity.java:27)
                                                                                                    	at com.belandsoft.orariGTT.View.MainActivity.onCreate(MainActivity.kt:185)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8000)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7984)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:223)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7656)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)`
