### ISSUE TITLE
Exception after giving the permission

### ISSUE THREAD

**Issue by panagorn** [yayaa/LocationManager#22]
Hello when i give the permission to access location i get this exception and the app always crashes

Process: com.panayiotis.locationdemo, PID: 29572
                                                                             Theme: themes:{}
                                                                             java.lang.AbstractMethodError: abstract method "com.google.android.gms.common.api.Api$zze com.google.android.gms.common.api.Api$zza.zza(android.content.Context, android.os.Looper, com.google.android.gms.common.internal.zzg, java.lang.Object, com.google.android.gms.common.api.GoogleApiClient$ConnectionCallbacks, com.google.android.gms.common.api.GoogleApiClient$OnConnectionFailedListener)"
                                                                                 at com.google.android.gms.common.api.GoogleApiClient$Builder.zza(Unknown Source)
                                                                                 at com.google.android.gms.common.api.GoogleApiClient$Builder.zzuQ(Unknown Source)
                                                                                 at com.google.android.gms.common.api.GoogleApiClient$Builder.build(Unknown Source)
                                                                                 at com.yayandroid.locationmanager.provider.GPServicesLocationProvider.get(GPServicesLocationProvider.java:75)
                                                                                 at com.yayandroid.locationmanager.LocationManager.getLocation(LocationManager.java:290)
                                                                                 at com.yayandroid.locationmanager.LocationManager.locationPermissionGranted(LocationManager.java:285)
                                                                                 at com.yayandroid.locationmanager.LocationManager.access$400(LocationManager.java:27)
                                                                                 at com.yayandroid.locationmanager.LocationManager$3.onPermissionsGranted(LocationManager.java:326)
                                                                                 at com.yayandroid.locationmanager.helper.PermissionManager.onRequestPermissionsResult(PermissionManager.java:122)
                                                                                 at com.yayandroid.locationmanager.LocationManager.onRequestPermissionsResult(LocationManager.java:155)
                                                                                 at com.yayandroid.locationmanager.LocationBaseActivity.onRequestPermissionsResult(LocationBaseActivity.java:77)
                                                                                 at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:6582)
                                                                                 at android.app.Activity.dispatchActivityResult(Activity.java:6460)
                                                                                 at android.app.ActivityThread.deliverResults(ActivityThread.java:3729)
                                                                                 at android.app.ActivityThread.handleSendResult(ActivityThread.java:3776)
                                                                                 at android.app.ActivityThread.-wrap16(ActivityThread.java)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1412)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:148)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5463)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by yayaa** [comment]
Seems like a GoogleApi issue but can you please give me some more info? 

Which device and OS version? 
And are you using LocationManager 1.1.5?

**Comment by panagorn** [comment]
was indeed something with google api. i upgraded to final version

**Comment by mahmooddagga** [comment]
+1
