### ISSUE TITLE
GPServicesLocationProvider class problem

### ISSUE THREAD

**Issue by azzimfarid** [yayaa/LocationManager#27]
Line number 216 is causing my app to crash please fix this issue.

**Comment by yayaa** [comment]
With this much explanation, that doesn't seem possible :) Provide some logs.

**Comment by azzimfarid** [comment]
My apologies here is the log:
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.location.LocationRequest com.yayandroid.locationmanager.LocationConfiguration.getLocationRequest()' on a null object reference
       at com.yayandroid.locationmanager.provider.GPServicesLocationProvider.requestLocationUpdate(GPServicesLocationProvider.java:216)
       at com.yayandroid.locationmanager.provider.GPServicesLocationProvider.onResult(GPServicesLocationProvider.java:180)
       at com.yayandroid.locationmanager.provider.GPServicesLocationProvider.onResult(GPServicesLocationProvider.java:28)
       at com.google.android.gms.internal.zzqe$zza.zzb(Unknown Source)
       at com.google.android.gms.internal.zzqe$zza.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5438)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

**Comment by yayaa** [comment]
Can you explain for me to understand the usecase clearly, how exactly it happens? 
Please also share your configuration object.

**Comment by yayaa** [comment]
I need a usecase to understand this, please specify the steps that you follow up to receive this bug. And also consider switching to v2.0.0 :)
