### ISSUE TITLE
NullPointerException in DefaultLocationProvider.java:249

### ISSUE THREAD

**Issue by patler** [yayaa/LocationManager#33]
com.yayandroid.locationmanager.provider.DefaultLocationProvider$3.onLocationChanged (DefaultLocationProvider.java:249)

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.yayandroid.locationmanager.LocationConfiguration.shouldKeepTracking()' on a null object reference
       at com.yayandroid.locationmanager.provider.DefaultLocationProvider$3.onLocationChanged(DefaultLocationProvider.java:249)
       at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:285)
       at android.location.LocationManager$ListenerTransport.-wrap0(LocationManager.java)
       at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:230)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

at line 249
`   if (configuration.shouldKeepTracking()) {
                requestUpdateLocation(configuration.getRequiredTimeInterval(), false);
            } else {
                locationManager.removeUpdates(locationChangeListener);
            }`

**Comment by yayaa** [comment]
Can you please provide your configuration and the usecase how this happens? Because in normal locationListener should've been removed already.

**Comment by patler** [comment]
Thanks.

Constants.TIME_UPDATE_GPS= 1800

@Override
public LocationConfiguration getLocationConfiguration() {
    return new LocationConfiguration()
            .keepTracking(true)
            .askForSettingsApi(false)
            .askForEnableGPS(false)
            .askForGooglePlayServices(false)
            .setMinAccuracy(200.0f)
            //aggiorna posizione ogni 30 min
            .setWaitPeriod(ProviderType.GOOGLE_PLAY_SERVICES,
Constants.TIME_UPDATE_GPS * 1000)
            .setWaitPeriod(ProviderType.GPS, Constants.TIME_UPDATE_GPS * 1000)
            .setWaitPeriod(ProviderType.NETWORK,
Constants.TIME_UPDATE_GPS * 1000)
            ;
}


2017-03-22 17:46 GMT+01:00 Yahya Bayramoğlu <notifications@github.com>:

**Comment by yayaa** [comment]
I still need the usecase @patler i need steps to follow up to get this error, because as i said in normal behaviour this should not happen. I need to be able reproduce this, in order to figure out the reason and fix. 
By the way, please also consider to use v2.0.0 which is just released :)

**Comment by patler** [comment]
Fixed with v2.0.0
