### ISSUE TITLE
I got error like Lcom/google/android/gms/location/LocationRequest;

### ISSUE THREAD

**Issue by shubhamkhuva** [yayaa/LocationManager#81]
I got error like describe below when i add firebase in my project, please help me to solve at SampleService.java
FATAL EXCEPTION: main
                                                                                                       Process: com.servicesaathi.servicesaathi_partner:SampleService, PID: 21255
                                                                                                       java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/location/LocationRequest;
                                                                                                           at com.yayandroid.locationmanager.configuration.Defaults.createDefaultLocationRequest(Defaults.java:40)
                                                                                                           at com.yayandroid.locationmanager.configuration.GooglePlayServicesConfiguration$Builder.<init>(GooglePlayServicesConfiguration.java:86)
                                                                                                           at com.yayandroid.locationmanager.configuration.Configurations.silentConfiguration(Configurations.java:33)
                                                                                                           at com.servicesaathi.servicesaathi_partner.service.SampleService.getLocationConfiguration(SampleService.java:50)
                                                                                                           at com.yayandroid.locationmanager.base.LocationBaseService.onStartCommand(LocationBaseService.java:23)
                                                                                                           at com.servicesaathi.servicesaathi_partner.service.SampleService.onStartCommand(SampleService.java:56)

**Comment by yayaa** [comment]
Which Google Play Services API do you use?

**Comment by shubhamkhuva** [comment]
This one is solved. Thank you

**Comment by yayaa** [comment]
Could you please share more information for documentation purposes? So that if anyone else faces the same problem can benefit.

What was the main reason? How it is resolved? @shubhamkhuva
