### ISSUE TITLE
Can't get location at all

### ISSUE THREAD

**Issue by LeonardoEmili** [yayaa/LocationManager#89]
I followed the pattern described in SampleActivity so I changed my activity from extending AppCompatActivity to LocationBaseActivity, so I've set to call getLocation() when the user clicks on a button, but I am not able to recive any Location Object, which I suppose to be in onLocationChanged, but I can't get any locations yet, where am I wrong?
Of course I added permissions in Manifest file.

### Configuration
```java
public class MapsActivity extends LocationBaseActivity {
 ...
 ...
     public void getLocation(View view) {
         getLocation();
     }

    @Override
        public void onLocationChanged(Location location) {
            Toast.makeText(this, location.getLatitude()+"", Toast.LENGTH_SHORT).show();
            Log.e("e", "change");
        }

    @Override
        public void onLocationFailed(int type) {
            Log.e("e", "fail+type");
         }

    @Override
        public LocationConfiguration getLocationConfiguration() {
            return Configurations.defaultConfiguration("Gimme the permission!", "Would you mind to turn GPS on?");
         }
}

**EDIT**: I noticed that I receive 1 as FailType in onLocationFailed(int type) method. Maybe could be useful.
```

### Logs
09/09 18:05:33: Launching app
No apk changes detected since last installation, skipping installation of /home/leoemili/AndroidStudioProjects/OrariSapienza/app/build/outputs/apk/debug/app-debug.apk
$ adb shell am force-stop com.sterbsociety.orarisapienza
$ adb shell am start -n "com.sterbsociety.orarisapienza/com.sterbsociety.orarisapienza.activities.WelcomeActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Client not ready yet..Connected to process 14246 on device xiaomi-mi_5-406b710
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
V/FA: Registered activity lifecycle callback
I/FirebaseInitProvider: FirebaseApp initialization successful
W/art: Found duplicate classes, falling back to interpreter mode for /data/user_de/0/com.google.android.gms/app_chimera/m/00000025/DynamiteLoader.apk
    Found duplicated class when checking oat files: 'Lcom/google/android/gms/common/annotation/KeepName;' in /data/user_de/0/com.google.android.gms/app_chimera/m/00000025/DynamiteLoader.apk and /data/app/com.sterbsociety.orarisapienza-1/base.apk:classes5.dex
V/FA: Cancelling job. JobID: 2134088475
I/DynamiteModule: Considering local module com.google.android.gms.flags:2 and remote module com.google.android.gms.flags:3
I/DynamiteModule: Selected remote version of com.google.android.gms.flags, version >= 3
V/FA: Collection enabled
V/FA: App package, google app id: com.sterbsociety.orarisapienza, 1:477749227600:android:c6644a210155dfd4
I/FA: App measurement is starting up, version: 12211
I/FA: To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
    To enable faster debug mode event logging run:
      adb shell setprop debug.firebase.analytics.app com.sterbsociety.orarisapienza
D/FA: Debug-level message logging enabled
W/System: ClassLoader referenced unknown path: 
V/FA: Connecting to remote service
W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
V/FA: Connection attempt already in progress
I/DynamiteModule: Considering local module com.google.android.gms.firebase_database:4 and remote module com.google.android.gms.firebase_database:6
    Selected remote version of com.google.android.gms.firebase_database, version >= 6
W/art: Found duplicate classes, falling back to interpreter mode for /data/user_de/0/com.google.android.gms/app_chimera/m/00000027/DynamiteModulesC.apk
    Found duplicated class when checking oat files: 'Landroid/support/v4/media/session/MediaSessionCompat$Token;' in /data/user_de/0/com.google.android.gms/app_chimera/m/00000027/DynamiteModulesC.apk and /data/app/com.sterbsociety.orarisapienza-1/base.apk:classes5.dex
V/FA: onActivityCreated
I/Timeline: Timeline: Activity_launch_request time:170601959 intent:Intent { cmp=com.sterbsociety.orarisapienza/.activities.MainActivity }
D/AccessibilityManager: current package=com.sterbsociety.orarisapienza, accessibility manager mIsFinalEnabled=false, mOptimizeEnabled=true, mIsUiAutomationEnabled=false, mIsInterestedPackage=false
W/DynamiteModule: Local module descriptor class for com.google.android.gms.crash not found.
I/DynamiteModule: Considering local module com.google.android.gms.crash:0 and remote module com.google.android.gms.crash:215
I/DynamiteModule: Selected remote version of com.google.android.gms.crash, version >= 215
V/FA: onActivityCreated
I/FirebaseCrashApiImpl: FirebaseCrashApiImpl created by ClassLoader ad[DexPathList[[zip file "/data/user_de/0/com.google.android.gms/app_chimera/m/00000027/DynamiteModulesC.apk"],nativeLibraryDirectories=[/data/user_de/0/com.google.android.gms/app_chimera/m/00000027/DynamiteModulesC.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]]
I/FirebaseCrash: FirebaseCrash reporting loaded - com.google.android.gms.internal.zzecv@21fb835
I/DynamiteModule: Considering local module com.google.android.gms.flags:2 and remote module com.google.android.gms.flags:3
    Selected remote version of com.google.android.gms.flags, version >= 3
I/art: Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$OnUnhandledKeyEventListenerWrapper>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/View$OnUnhandledKeyEventListener;
        at void androidx.core.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, androidx.core.view.OnApplyWindowInsetsListener) (ViewCompat.java:2203)
        at android.view.ViewGroup androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:637)
        at void androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:518)
        at void androidx.appcompat.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:466)
        at void androidx.appcompat.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:140)
        at void com.sterbsociety.orarisapienza.activities.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:51)
        at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6858)
        at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1119)
        at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2677)
        at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2785)
        at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
        at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1532)
        at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
        at void android.os.Looper.loop() (Looper.java:163)
        at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6337)
        at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:880)
        at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:770)
        at void de.robv.android.xposed.XposedBridge.main(java.lang.String[]) (XposedBridge.java:107)
    Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/com.sterbsociety.orarisapienza-1/base.apk"],nativeLibraryDirectories=[/data/app/com.sterbsociety.orarisapienza-1/lib/arm64, /data/app/com.sterbsociety.orarisapienza-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
        at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
        at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
        at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
        at void androidx.core.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, androidx.core.view.OnApplyWindowInsetsListener) (ViewCompat.java:2203)
        at android.view.ViewGroup androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:637)
        at void androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:518)
        at void androidx.appcompat.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:466)
        at void androidx.appcompat.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:140)
        at void com.sterbsociety.orarisapienza.activities.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:51)
        at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6858)
        at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1119)
        at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2677)
        at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2785)
        at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
        at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1532)
        at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
        at void android.os.Looper.loop() (Looper.java:163)
        at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6337)
        at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
        at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:880)
        at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:770)
        at void de.robv.android.xposed.XposedBridge.main(java.lang.String[]) (XposedBridge.java:107)
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
W/DynamiteModule: Local module descriptor class for com.google.android.gms.crash not found.
I/FirebaseCrashApiImpl: FirebaseCrash reporting API initialized
I/FirebaseCrash: FirebaseCrash reporting initialized com.google.android.gms.internal.zzecv@21fb835
D/FirebaseCrash: Firebase Analytics Listener for Firebase Crash is initialized
I/art: Do partial code cache collection, code=28KB, data=29KB
    After code cache collection, code=27KB, data=29KB
    Increasing code cache capacity to 128KB
I/art: Do partial code cache collection, code=34KB, data=55KB
I/art: After code cache collection, code=34KB, data=55KB
    Increasing code cache capacity to 256KB
    Compiler allocated 6MB to compile void android.widget.TextView.<init>(android.content.Context, android.util.AttributeSet, int, int)
W/art: Found duplicate classes, falling back to interpreter mode for /data/user_de/0/com.google.android.gms/app_chimera/m/00000023/AdsDynamite.apk
    Found duplicated class when checking oat files: 'Lb;' in /data/user_de/0/com.google.android.gms/app_chimera/m/00000023/AdsDynamite.apk and /data/app/com.google.android.gms-1/base.apk
D/DynamitePackage: Instantiated singleton DynamitePackage.
D/DynamitePackage: Instantiating com.google.android.gms.ads.ChimeraAdManagerCreatorImpl
I/Ads: Updating ad debug logging enablement.
E/Ads: Fail to get isAdIdFakeForDebugLogging
    java.io.IOException: Connection failure
        at com.google.android.gms.ads.identifier.a.a(:com.google.android.gms.dynamite_adsdynamite@12874025@12.8.74 (040408-204998136):125)
        at com.google.android.gms.ads.identifier.a.a(:com.google.android.gms.dynamite_adsdynamite@12874025@12.8.74 (040408-204998136):19)
        at com.google.android.gms.ads.identifier.a.b(:com.google.android.gms.dynamite_adsdynamite@12874025@12.8.74 (040408-204998136):148)
        at com.google.android.gms.ads.internal.util.d.a(:com.google.android.gms.dynamite_adsdynamite@12874025@12.8.74 (040408-204998136):6)
        at com.google.android.gms.ads.internal.util.b.run(:com.google.android.gms.dynamite_adsdynamite@12874025@12.8.74 (040408-204998136):4)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)
W/Ads: Update ad debug logging enablement as false
I/Ads: Starting ad request.
I/Ads: This request is sent from a test device.
W/art: Before Android 4.1, method double java.util.concurrent.ThreadLocalRandom.internalNextDouble(double, double) would have incorrectly overridden the package-private method in java.util.Random
    Before Android 4.1, method int java.util.concurrent.ThreadLocalRandom.internalNextInt(int, int) would have incorrectly overridden the package-private method in java.util.Random
    Before Android 4.1, method long java.util.concurrent.ThreadLocalRandom.internalNextLong(long, long) would have incorrectly overridden the package-private method in java.util.Random
D/Distance: 0.1991928811087621
I/WebViewFactory: Loading com.android.chrome version 69.0.3497.86 (code 349708652)
I/FA: Tag Manager is not found and thus will not be used
D/FA: Logging event (FE): ad_query(_aq), Bundle[{firebase_event_origin(_o)=am, ad_event_id(_aeid)=-3381079055120313008}]
V/FA: Connection attempt already in progress
V/FA: Connection attempt already in progress
V/FA: Activity resumed, time: 351895347
D/FA: Logging event (FE): screen_view(_vs), Bundle[{firebase_event_origin(_o)=auto, firebase_screen_class(_sc)=MainActivity, firebase_screen_id(_si)=-3381079055120313007}]
I/art: Rejecting re-init on previously-failed class java.lang.Class<uJ>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/webkit/TracingController;
        at java.lang.Class java.lang.Class.classForName!(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:-2)
        at java.lang.Class java.lang.Class.forName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:400)
        at java.lang.Class android.webkit.WebViewFactory.getProviderClass() (WebViewFactory.java:349)
        at android.webkit.WebViewFactoryProvider android.webkit.WebViewFactory.getProvider() (WebViewFactory.java:194)
        at android.webkit.CookieManager android.webkit.CookieManager.getInstance() (CookieManager.java:39)
        at android.webkit.CookieManager com.google.android.gms.ads.internal.util.ac.c(android.content.Context) (:com.google.android.gms.dynamite_adsdynamite@12874025@12.8.74 (040408-204998136):4)
        at java.lang.Object com.google.android.gms.ads.internal.g.call() (:com.google.android.gms.dynamite_adsdynamite@12874025@12.8.74 (040408-204998136):9)
        at void java.util.concurrent.FutureTask.run() (FutureTask.java:237)
        at void java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) (ThreadPoolExecutor.java:1133)
        at void java.util.concurrent.ThreadPoolExecutor$Worker.run() (ThreadPoolExecutor.java:607)
        at void java.lang.Thread.run() (Thread.java:760)
    Caused by: java.lang.ClassNotFoundException: Didn't find class "android.webkit.TracingController" on path: DexPathList[[zip file "/data/app/com.android.chrome-1/base.apk"],nativeLibraryDirectories=[/data/app/com.android.chrome-1/lib/arm64, /data/app/com.android.chrome-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
        at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
        at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
        at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
        at java.lang.Class java.lang.Class.classForName!(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:-2)
        at java.lang.Class java.lang.Class.forName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:400)
        at java.lang.Class android.webkit.WebViewFactory.getProviderClass() (WebViewFactory.java:349)
        at android.webkit.WebViewFactoryProvider android.webkit.WebViewFactory.getProvider() (WebViewFactory.java:194)
        at android.webkit.CookieManager android.webkit.CookieManager.getInstance() (CookieManager.java:39)
        at android.webkit.CookieManager com.google.android.gms.ads.internal.util.ac.c(android.content.Context) (:com.google.android.gms.dynamite_adsdynamite@12874025@12.8.74 (040408-204998136):4)
        at java.lang.Object com.google.android.gms.ads.internal.g.call() (:com.google.android.gms.dynamite_adsdynamite@12874025@12.8.74 (040408-204998136):9)
        at void java.util.concurrent.FutureTask.run() (FutureTask.java:237)
        at void java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) (ThreadPoolExecutor.java:1133)
        at void java.util.concurrent.ThreadPoolExecutor$Worker.run() (ThreadPoolExecutor.java:607)
        at void java.lang.Thread.run() (Thread.java:760)
V/FA: Connection attempt already in progress
D/FA: Connected to remote service
V/FA: Processing queued up service tasks: 5
I/cr_LibraryLoader: Time to load native libraries: 30 ms (timestamps 2686-2716)
E/cr_VariationsUtils: Failed reading seed file "/data/user/0/com.sterbsociety.orarisapienza/app_webview/variations_seed_new": /data/user/0/com.sterbsociety.orarisapienza/app_webview/variations_seed_new (No such file or directory)
I/chromium: [INFO:library_loader_hooks.cc(36)] Chromium logging enabled: level = 0, default verbosity = 0
I/cr_LibraryLoader: Expected native library version number "69.0.3497.86", actual native library version number "69.0.3497.86"
I/Adreno: QUALCOMM build                   : 4f3d4bc, I07a8b16b27
    Build Date                       : 10/26/17
    OpenGL ES Shader Compiler Version: XE031.09.00.04
    Local Branch                     : mybranch28842968
    Remote Branch                    : quic/gfx-adreno.lnx.1.0.r5-rel
    Remote Branch                    : NONE
    Reconstruct Branch               : NOTHING
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 1
I/cr_BrowserStartup: Initializing chromium process, singleProcess=true
W/ResourceType: Failure getting entry for 0x7f1204c5 (t=17 e=1221) (error -2147483647)
I/chromium: [INFO:aw_field_trial_creator.cc(54)] First-WebView-Experiment not found
D/EgretLoader: EgretLoader(Context context)
    The context is not activity
W/ContentCatcher: Failed to notify a WebView
E/libEGL: validate_display:99 error 3008 (EGL_BAD_DISPLAY)
W/cr_media: Requires BLUETOOTH permission
W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities: Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
    Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
    Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities: Unsupported mime video/x-ms-wmv
W/VideoCapabilities: Unsupported mime video/x-ms-wmv
W/VideoCapabilities: Unsupported mime video/divx
W/VideoCapabilities: Unsupported mime video/divx311
W/VideoCapabilities: Unsupported mime video/divx4
W/AudioCapabilities: Unsupported mime audio/dsd
W/AudioCapabilities: Unsupported mime audio/dts
W/AudioCapabilities: Unsupported mime audio/32KADPCM
W/VideoCapabilities: Unsupported mime video/mp4v-esdp
I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@a823ee0
I/Timeline: Timeline: Activity_launch_request time:170605977 intent:Intent { cmp=com.sterbsociety.orarisapienza/.activities.MapsActivity }
I/Ads: Scheduling ad refresh 70000 milliseconds from now.
I/DynamiteModule: Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:300
    Selected remote version of com.google.android.gms.ads.dynamite, version >= 300
W/art: Found duplicate classes, falling back to interpreter mode for /data/user_de/0/com.google.android.gms/app_chimera/m/00000023/AdsDynamite.apk
    Found duplicated class when checking oat files: 'Laai;' in /data/user_de/0/com.google.android.gms/app_chimera/m/00000023/AdsDynamite.apk and /data/app/com.android.chrome-1/base.apk
D/FA: Logging event (FE): ad_impression(_ai), Bundle[{firebase_event_origin(_o)=am, firebase_screen_class(_sc)=MainActivity, firebase_screen_id(_si)=-3381079055120313007, ad_event_id(_aeid)=-3381079055120313000}]
D/EgretLoader: EgretLoader(Context context)
    The context is not activity
V/FA: Not logging ad unit exposure. Less than 1000 ms. exposure: 59
V/FA: Not logging ad exposure. Less than 1000 ms. exposure: 59
V/FA: Recording user engagement, ms: 3631
V/FA: Activity paused, time: 351898974
V/FA: Not logging ad unit exposure. No active activity
    Not logging ad exposure. No active activity
D/FA: Logging event (FE): user_engagement(_e), Bundle[{firebase_event_origin(_o)=auto, engagement_time_msec(_et)=3631, firebase_screen_class(_sc)=MainActivity, firebase_screen_id(_si)=-3381079055120313007}]
V/FA: onActivityCreated
I/zzbz: Making Creator dynamically
I/DynamiteModule: Considering local module com.google.android.gms.maps_dynamite:0 and remote module com.google.android.gms.maps_dynamite:220
I/DynamiteModule: Selected remote version of com.google.android.gms.maps_dynamite, version >= 220
W/art: Found duplicate classes, falling back to interpreter mode for /data/user_de/0/com.google.android.gms/app_chimera/m/00000029/MapsDynamite.apk
    Found duplicated class when checking oat files: 'Lab;' in /data/user_de/0/com.google.android.gms/app_chimera/m/00000029/MapsDynamite.apk and /data/app/com.android.chrome-1/base.apk
I/Google Maps Android API: Google Play services client version: 12211000
I/Google Maps Android API: Google Play services package version: 12874025
I/art: Do full code cache collection, code=125KB, data=121KB
I/art: After code cache collection, code=117KB, data=99KB
E/art: The String#value field is not present on Android versions >= 6.0
I/art: Do partial code cache collection, code=118KB, data=100KB
I/art: After code cache collection, code=118KB, data=100KB
    Increasing code cache capacity to 512KB
V/FA: Activity resumed, time: 351900001
D/FA: Logging event (FE): screen_view(_vs), Bundle[{firebase_event_origin(_o)=auto, firebase_previous_class(_pc)=MainActivity, firebase_previous_id(_pi)=-3381079055120313007, firebase_screen_class(_sc)=MapsActivity, firebase_screen_id(_si)=-3381079055120312997}]
I/Choreographer: Skipped 60 frames!  The application may be doing too much work on its main thread.
I/art: Compiler allocated 5MB to compile void com.google.maps.api.android.lib6.gmm6.vector.bs.b(javax.microedition.khronos.opengles.GL10)
D/FA: Logging event (FE): ad_activeview(_aa), Bundle[{firebase_event_origin(_o)=am, firebase_screen_class(_sc)=MapsActivity, firebase_screen_id(_si)=-3381079055120312997, ad_event_id(_aeid)=4060147869011046400}]
W/OpenGLRenderer: cuilf destroyHardwareResources 545 RenderNode: 0x7f7d3a9000, layer: 0x7f4a891500
    cuilf pushLayerUpdate 309 delete mLayer: 0x7f6105b700, RenderLayer: 0x7f4fafdc00
W/OpenGLRenderer: cuilf pushLayerUpdate 309 delete mLayer: 0x7f4a891900, RenderLayer: 0x7f4b521c00
I/art: Do full code cache collection, code=241KB, data=249KB
I/art: After code cache collection, code=198KB, data=193KB
W/DynamiteModule: Local module descriptor class for com.google.android.gms.googlecertificates not found.
I/DynamiteModule: Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:4
    Selected remote version of com.google.android.gms.googlecertificates, version >= 4
W/art: Found duplicate classes, falling back to interpreter mode for /data/user_de/0/com.google.android.gms/app_chimera/m/00000028/GoogleCertificates.apk
    Found duplicated class when checking oat files: 'La;' in /data/user_de/0/com.google.android.gms/app_chimera/m/00000028/GoogleCertificates.apk and /data/app/com.android.chrome-1/base.apk
I/art: Do partial code cache collection, code=217KB, data=218KB
I/art: After code cache collection, code=211KB, data=212KB
    Increasing code cache capacity to 1024KB
W/OpenGLRenderer: Incorrectly called buildLayer on View: AppCompatImageButton, destroying layer...
    cuilf destroyHardwareResources 545 RenderNode: 0x7f8ba8dc00, layer: 0x7f4a891700
W/OpenGLRenderer: cuilf destroyHardwareResources 545 RenderNode: 0x7f4fafdc00, layer: 0x7f4a891a00
    cuilf pushLayerUpdate 309 delete mLayer: 0x7f4faf4500, RenderLayer: 0x7f7d3a9000
I/FirebaseCrash: Sending crashes
V/FA: Inactivity, disconnecting from the service

**Comment by leoemili** [comment]
Any idea?

**Comment by yayaa** [comment]
Hey, sorry didn't have time to look into, but log output looks so polluted, could you please share only relevant ones? Make sure you set your App's package name on `debuggable process` for logcat and have `Show only selected application` selected on filter. 

It should tell you where it was broken, or pending... That can give us some idea what might be going wrong or missing.
