### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by vikramsingh1985** [yayaa/LocationManager#97]
I have Migrate to androidX, then i am facing this issue.
 com.google.android.gms.location.LocationServices.<clinit>(Unknown Source)
        at com.yayandroid.locationmanager.providers.locationprovider.GooglePlayServicesLocationSource.<init>(GooglePlayServicesLocationSource.java:48)
        at com.yayandroid.locationmanager.providers.locationprovider.GooglePlayServicesLocationProvider.getSourceProvider(GooglePlayServicesLocationProvider.java:287)
        at com.yayandroid.locationmanager.providers.locationprovider.GooglePlayServicesLocationProvider.get(GooglePlayServicesLocationProvider.java:72)
        at com.yayandroid.locationmanager.providers.locationprovider.DispatcherLocationProvider.getLocationFromGooglePlayServices(DispatcherLocationProvider.java:187)
        at com.yayandroid.locationmanager.providers.locationprovider.DispatcherLocationProvider.checkGooglePlayServicesAvailability(DispatcherLocationProvider.java:133)
        at com.yayandroid.locationmanager.providers.locationprovider.DispatcherLocationProvider.get(DispatcherLocationProvider.java:113)
        at com.yayandroid.locationmanager.LocationManager.permissionGranted(LocationManager.java:244)
        at com.yayandroid.locationmanager.LocationManager.askForPermission(LocationManager.java:222)
        at com.yayandroid.locationmanager.LocationManager.get(LocationManager.java:210)
        at com.yayandroid.locationmanager.base.LocationBaseActivity.getLocation(LocationBaseActivity.java:26)

**Comment by yayaa** [comment]
Just released v2.2.0 with all dependencies updated - please give it a try, that should solve this issue.
